server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    autoindex on;

    location ~* \.aix$ {
        add_header Content-Type 'application/octet-stream';
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
